test(ci): make the workflow fail to exercise rewindr capture

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -11,7 +11,6 @@ jobs:
           secrets: ${{ toJSON(secrets) }}
 
       - name: Run broken test
-        run: echo "Running something very important"
-        # run: |
-        #   echo "Generating critical error..."
-        #   exit 1
+        run: |
+          echo "Generating critical error..."
+          exit 1
